# Format from https://dev.to/alexeagleson/docker-for-javascript-developers-41me
version: '3.8'
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8070:8070"
    volumes:
      - ./:/usr/src/app/

  postgres:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    volumes:
      - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
  pgadmin-compose:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "test@test.com"
            PGADMIN_DEFAULT_PASSWORD: "password"
        ports:
            - "16543:80"
        depends_on:
            - postgres